const OPENCLAW_TEAM = [
  {
    id: 1,
    name: "Robin Waslander",
    role: "Mblock BV",
    avatar: "https://github.com/hydro13.png",
    status: "unread",
  },
  {
    id: 2,
    name: "Tak Hoffman",
    role: "Contributor",
    avatar: "https://github.com/Takhoffman.png",
    status: "unread",
  },
  {
    id: 3,
    name: "Harold Hunt",
    role: "GIPHY",
    avatar: "https://github.com/huntharo.png",
    status: "unread",
  },
  {
    id: 4,
    name: "Devin Robison",
    role: "Contributor",
    avatar: "https://github.com/drobison00.png",
    status: "unread",
  },
  {
    id: 5,
    name: "Frank Yang",
    role: "Contributor",
    avatar: "https://github.com/frankekn.png",
    status: "unread",
  },
  {
    id: 6,
    name: "Tyler Yust",
    role: "Contributor",
    avatar: "https://github.com/tyler6204.png",
    status: "unread",
  },
  {
    id: 7,
    name: "Mariano",
    role: "Contributor",
    avatar: "https://github.com/mbelinky.png",
    status: "unread",
  },
  {
    id: 8,
    name: "Kenny Xie",
    role: "Contributor",
    avatar: "https://github.com/aquaright1.png",
    status: "unread",
  },
  {
    id: 9,
    name: "Saurabh Mishra",
    role: "Contributor",
    avatar: "https://github.com/bugkill3r.png",
    status: "unread",
  },
  {
    id: 10,
    name: "Brad Groux",
    role: "Contributor",
    avatar: "https://github.com/BradGroux.png",
    status: "unread",
  },
  {
    id: 11,
    name: "Neerav Makwana",
    role: "Contributor",
    avatar: "https://github.com/neeravmakwana.png",
    status: "unread",
  },
  {
    id: 12,
    name: "Sid Uppal",
    role: "Contributor",
    avatar: "https://github.com/SidU.png",
    status: "unread",
  },
];

const OPENCLAW_ME = {
  id: 0,
  name: "Gustavo Santana",
  role: "Contributor",
  avatar: "https://github.com/gumadeiras.png",
  status: "posted",
};

const OPENCLAW_PENDING_POST = {
  text: "Matrix direct messages now route to the correct room — fixes misdelivered outbound messages in federated setups.",
  ticket: { title: "fix(matrix): align outbound direct-room selection", status: "MERGED" },
  landedAt: Date.now() - 2 * 60 * 1000,
  autoPostAt: Date.now() + 8 * 60 * 1000,
};

const OPENCLAW_STORIES = [
  // Robin Waslander — 11 PRs
  {
    id: 1,
    authorId: 1,
    author: "Robin Waslander",
    role: "Mblock BV",
    avatar: "https://github.com/hydro13.png",
    time: "1h ago",
    text: "Agents now handle unexpected stop reasons gracefully — no more silent crashes mid-conversation.",
    pr: {
      title: "fix(agents): handle unhandled stop reasons gracefully instead of crashing",
      status: "MERGED",
      number: "#56639",
      url: "https://github.com/openclaw/openclaw/pull/56639",
    },
    reactions: { fire: 7, eyes: 3, hand: 1 },
  },
  {
    id: 2,
    authorId: 1,
    author: "Robin Waslander",
    role: "Mblock BV",
    avatar: "https://github.com/hydro13.png",
    time: "2h ago",
    text: "Changelog now reflects all recent fixes — cleaner release notes for contributors tracking changes.",
    pr: {
      title: "chore: backfill changelog entries for recent fixes",
      status: "MERGED",
      number: "#56625",
      url: "https://github.com/openclaw/openclaw/pull/56625",
    },
    reactions: { fire: 1, eyes: 2, hand: 0 },
  },
  {
    id: 3,
    authorId: 1,
    author: "Robin Waslander",
    role: "Mblock BV",
    avatar: "https://github.com/hydro13.png",
    time: "3h ago",
    text: "Telegram bot no longer crashes on empty replies — silently skips instead of throwing GrammyError 400.",
    pr: {
      title: "fix(telegram): skip empty text replies instead of crashing with GrammyError 400",
      status: "MERGED",
      number: "#56620",
      url: "https://github.com/openclaw/openclaw/pull/56620",
    },
    reactions: { fire: 4, eyes: 1, hand: 0 },
  },
  {
    id: 4,
    authorId: 1,
    author: "Robin Waslander",
    role: "Mblock BV",
    avatar: "https://github.com/hydro13.png",
    time: "3h ago",
    text: "Auto-reply no longer leaks raw JSON to users — NO_REPLY payloads are suppressed before delivery.",
    relevant: "Relevant to your work on channel delivery — this fixes payload formatting before messages reach users",
    pr: {
      title: "fix(auto-reply): suppress JSON-wrapped NO_REPLY payloads before channel delivery",
      status: "MERGED",
      number: "#56612",
      url: "https://github.com/openclaw/openclaw/pull/56612",
    },
    reactions: { fire: 5, eyes: 2, hand: 0 },
  },
  {
    id: 5,
    authorId: 1,
    author: "Robin Waslander",
    role: "Mblock BV",
    avatar: "https://github.com/hydro13.png",
    time: "4h ago",
    text: "Long Telegram messages now split at word boundaries — no more cut-off words in multi-part replies.",
    relevant: "Relevant to your work on channel delivery — improves message formatting in the same pipeline you're touching",
    pr: {
      title: "fix(telegram): split long messages at word boundaries instead of mid-word",
      status: "MERGED",
      number: "#56595",
      url: "https://github.com/openclaw/openclaw/pull/56595",
    },
    reactions: { fire: 3, eyes: 1, hand: 0 },
  },
  {
    id: 6,
    authorId: 1,
    author: "Robin Waslander",
    role: "Mblock BV",
    avatar: "https://github.com/hydro13.png",
    time: "4h ago",
    text: "Telegram replies now validate message IDs before sending — prevents API errors on stale threads.",
    pr: {
      title: "fix(telegram): validate replyToMessageId before sending to Telegram API",
      status: "MERGED",
      number: "#56587",
      url: "https://github.com/openclaw/openclaw/pull/56587",
    },
    reactions: { fire: 2, eyes: 1, hand: 0 },
  },
  {
    id: 7,
    authorId: 1,
    author: "Robin Waslander",
    role: "Mblock BV",
    avatar: "https://github.com/hydro13.png",
    time: "5h ago",
    text: "BlueBubbles integration no longer crashes on null text — debounce flush is properly guarded.",
    pr: {
      title: "fix(bluebubbles): guard debounce flush against null text",
      status: "MERGED",
      number: "#56573",
      url: "https://github.com/openclaw/openclaw/pull/56573",
    },
    reactions: { fire: 2, eyes: 0, hand: 0 },
  },
  {
    id: 8,
    authorId: 1,
    author: "Robin Waslander",
    role: "Mblock BV",
    avatar: "https://github.com/hydro13.png",
    time: "5h ago",
    text: "Gemini 3.1 models now resolve correctly across all Google provider aliases — no more model-not-found errors.",
    pr: {
      title: "fix(google): resolve Gemini 3.1 models for all Google provider aliases",
      status: "MERGED",
      number: "#56567",
      url: "https://github.com/openclaw/openclaw/pull/56567",
    },
    reactions: { fire: 6, eyes: 3, hand: 0 },
  },
  {
    id: 9,
    authorId: 1,
    author: "Robin Waslander",
    role: "Mblock BV",
    avatar: "https://github.com/hydro13.png",
    time: "5h ago",
    text: "CLI tab completion no longer errors on fresh zsh shells — compdef registration deferred until ready.",
    pr: {
      title: "fix(cli): defer zsh compdef registration until compinit is available",
      status: "MERGED",
      number: "#56555",
      url: "https://github.com/openclaw/openclaw/pull/56555",
    },
    reactions: { fire: 3, eyes: 1, hand: 0 },
  },
  {
    id: 10,
    authorId: 1,
    author: "Robin Waslander",
    role: "Mblock BV",
    avatar: "https://github.com/hydro13.png",
    time: "6h ago",
    text: "Web search API keys are now audited across all bundled providers — tighter security for search integrations.",
    pr: {
      title: "fix(security): audit web search keys for all bundled providers",
      status: "MERGED",
      number: "#56540",
      url: "https://github.com/openclaw/openclaw/pull/56540",
    },
    reactions: { fire: 4, eyes: 5, hand: 0 },
  },
  {
    id: 11,
    authorId: 1,
    author: "Robin Waslander",
    role: "Mblock BV",
    avatar: "https://github.com/hydro13.png",
    time: "8h ago",
    text: "FAQ no longer links to dead Xfinity SSL troubleshooting pages — broken links cleaned up.",
    pr: {
      title: "fix(docs): remove broken Xfinity SSL troubleshooting links from FAQ",
      status: "MERGED",
      number: "#56500",
      url: "https://github.com/openclaw/openclaw/pull/56500",
    },
    reactions: { fire: 1, eyes: 0, hand: 0 },
  },
  // Tak Hoffman — 4 PRs
  {
    id: 12,
    authorId: 2,
    author: "Tak Hoffman",
    role: "Contributor",
    avatar: "https://github.com/Takhoffman.png",
    time: "6h ago",
    text: "Dashboard setup now guides users with clearer prompts — fewer drop-offs at onboarding.",
    pr: {
      title: "Improve dashboard setup command copy UX",
      status: "MERGED",
      number: "#56551",
      url: "https://github.com/openclaw/openclaw/pull/56551",
    },
    reactions: { fire: 4, eyes: 2, hand: 0 },
  },
  {
    id: 13,
    authorId: 2,
    author: "Tak Hoffman",
    role: "Contributor",
    avatar: "https://github.com/Takhoffman.png",
    time: "7h ago",
    text: "Dev builds now automatically rebuild dist after HEAD changes — no more stale bundles during development.",
    pr: {
      title: "fix(dev): rebuild dist after HEAD changes",
      status: "MERGED",
      number: "#56510",
      url: "https://github.com/openclaw/openclaw/pull/56510",
    },
    reactions: { fire: 3, eyes: 1, hand: 0 },
  },
  {
    id: 14,
    authorId: 2,
    author: "Tak Hoffman",
    role: "Contributor",
    avatar: "https://github.com/Takhoffman.png",
    time: "9h ago",
    text: "CI shard counts are now aligned between bun and Windows runners — consistent parallel test execution.",
    pr: {
      title: "ci: align bun shard counts with windows",
      status: "MERGED",
      number: "#56429",
      url: "https://github.com/openclaw/openclaw/pull/56429",
    },
    reactions: { fire: 2, eyes: 1, hand: 0 },
  },
  {
    id: 15,
    authorId: 2,
    author: "Tak Hoffman",
    role: "Contributor",
    avatar: "https://github.com/Takhoffman.png",
    time: "23h ago",
    text: "Module-bound regression tests no longer flake — stabilized exact matching in CI pipeline.",
    pr: {
      title: "fix(ci): stabilize module-bound exact regressions",
      status: "MERGED",
      number: "#56085",
      url: "https://github.com/openclaw/openclaw/pull/56085",
    },
    reactions: { fire: 2, eyes: 0, hand: 0 },
  },
  // Harold Hunt — 1 PR
  {
    id: 16,
    authorId: 3,
    author: "Harold Hunt",
    role: "GIPHY",
    avatar: "https://github.com/huntharo.png",
    time: "2h ago",
    text: "xAI provider now uses the Responses API with native search — unlocks grounded web results for Grok models.",
    pr: {
      title: "fix(xai): move bundled provider to Responses and add x_search",
      status: "MERGED",
      number: "#56048",
      url: "https://github.com/openclaw/openclaw/pull/56048",
    },
    reactions: { fire: 6, eyes: 3, hand: 1 },
  },
  // Devin Robison — 1 PR
  {
    id: 17,
    authorId: 4,
    author: "Devin Robison",
    role: "Contributor",
    avatar: "https://github.com/drobison00.png",
    time: "3h ago",
    text: "OpenAI-compatible API routes now enforce operator.write scopes — closes a permission bypass in HTTP layer.",
    pr: {
      title: "Fix HTTP OpenAI-compatible routes missing operator.write scope checks",
      status: "MERGED",
      number: "#56618",
      url: "https://github.com/openclaw/openclaw/pull/56618",
    },
    reactions: { fire: 5, eyes: 4, hand: 0 },
  },
  // Frank Yang — 1 PR
  {
    id: 18,
    authorId: 5,
    author: "Frank Yang",
    role: "Contributor",
    avatar: "https://github.com/frankekn.png",
    time: "7h ago",
    text: "ACP bindings now refresh after runtime exits — no more stale connections when processes restart.",
    pr: {
      title: "fix(acp): repair stale bindings after runtime exits",
      status: "MERGED",
      number: "#56476",
      url: "https://github.com/openclaw/openclaw/pull/56476",
    },
    reactions: { fire: 3, eyes: 2, hand: 0 },
  },
  // Tyler Yust — 1 PR
  {
    id: 19,
    authorId: 6,
    author: "Tyler Yust",
    role: "Contributor",
    avatar: "https://github.com/tyler6204.png",
    time: "12h ago",
    text: "Extension channels now receive subagent announcements — plugins stay in sync with agent lifecycle events.",
    pr: {
      title: "fix: include extension channels in subagent announce delivery path",
      status: "MERGED",
      number: "#56348",
      url: "https://github.com/openclaw/openclaw/pull/56348",
    },
    reactions: { fire: 2, eyes: 1, hand: 0 },
  },
  // Mariano — 1 PR
  {
    id: 20,
    authorId: 7,
    author: "Mariano",
    role: "Contributor",
    avatar: "https://github.com/mbelinky.png",
    time: "15h ago",
    text: "Daemon probes now surface close reasons — easier debugging when health checks fail unexpectedly.",
    pr: {
      title: "fix(daemon): surface probe close reasons",
      status: "MERGED",
      number: "#56282",
      url: "https://github.com/openclaw/openclaw/pull/56282",
    },
    reactions: { fire: 2, eyes: 3, hand: 0 },
  },
  // Kenny Xie — 1 PR
  {
    id: 21,
    authorId: 8,
    author: "Kenny Xie",
    role: "Contributor",
    avatar: "https://github.com/aquaright1.png",
    time: "15h ago",
    text: "Matrix plugin no longer crashes from mixed SDK entrypoints — resolves module conflict on startup.",
    pr: {
      title: "fix(matrix): prevent mixed matrix-js-sdk entrypoints from crashing plugin load",
      status: "MERGED",
      number: "#56273",
      url: "https://github.com/openclaw/openclaw/pull/56273",
    },
    reactions: { fire: 3, eyes: 2, hand: 1 },
  },
  // Saurabh Mishra — 1 PR
  {
    id: 22,
    authorId: 9,
    author: "Saurabh Mishra",
    role: "Contributor",
    avatar: "https://github.com/bugkill3r.png",
    time: "11h ago",
    text: "Telegram model selector now shows human-readable names — no more cryptic model IDs in the picker.",
    pr: {
      title: "fix: display model name instead of ID in Telegram model selector",
      status: "MERGED",
      number: "#56175",
      url: "https://github.com/openclaw/openclaw/pull/56175",
    },
    reactions: { fire: 4, eyes: 1, hand: 0 },
  },
  // Brad Groux — 1 PR
  {
    id: 23,
    authorId: 10,
    author: "Brad Groux",
    role: "Contributor",
    avatar: "https://github.com/BradGroux.png",
    time: "19h ago",
    text: "Teams messages now deliver progressively with proper streaming config — smoother real-time responses.",
    relevant: "Relevant to your work on channel delivery — adds streaming support to the Teams delivery path",
    pr: {
      title: "fix(msteams): wire blockStreaming config and onBlockReply for progressive message delivery",
      status: "MERGED",
      number: "#56134",
      url: "https://github.com/openclaw/openclaw/pull/56134",
    },
    reactions: { fire: 3, eyes: 2, hand: 0 },
  },
  // Neerav Makwana — 1 PR
  {
    id: 24,
    authorId: 11,
    author: "Neerav Makwana",
    role: "Contributor",
    avatar: "https://github.com/neeravmakwana.png",
    time: "21h ago",
    text: "Gateway now reuses session workspaces for tool loading — faster HTTP tool execution with less overhead.",
    pr: {
      title: "gateway: reuse session workspace for HTTP tool loading",
      status: "MERGED",
      number: "#56101",
      url: "https://github.com/openclaw/openclaw/pull/56101",
    },
    reactions: { fire: 2, eyes: 1, hand: 0 },
  },
  // Sid Uppal — 1 PR
  {
    id: 25,
    authorId: 12,
    author: "Sid Uppal",
    role: "Contributor",
    avatar: "https://github.com/SidU.png",
    time: "21h ago",
    text: "Teams stream state now resets after tool calls — no more dropped messages during multi-step workflows.",
    relevant: "Relevant to your work on channel delivery — prevents message loss during multi-step tool flows",
    pr: {
      title: "fix(msteams): reset stream state after tool calls to prevent message loss",
      status: "MERGED",
      number: "#56071",
      url: "https://github.com/openclaw/openclaw/pull/56071",
    },
    reactions: { fire: 4, eyes: 2, hand: 0 },
  },
  // Gustavo Santana (ME) — 1 posted story
  {
    id: 26,
    authorId: 0,
    author: "Gustavo Santana",
    role: "Contributor",
    avatar: "https://github.com/gumadeiras.png",
    time: "24h ago",
    text: "Bundled runtime deps now stage correctly after updates — no more missing dependencies in production builds.",
    pr: {
      title: "fix(diffs): stage bundled runtime deps after updates",
      status: "MERGED",
      number: "#56077",
      url: "https://github.com/openclaw/openclaw/pull/56077",
    },
    reactions: { fire: 3, eyes: 1, hand: 0 },
  },
];

const MINIMAX_TEAM = [
  {
    id: 1,
    name: "divitkashyap",
    role: "Contributor",
    avatar: "https://github.com/divitkashyap.png",
    status: "unread",
  },
  {
    id: 2,
    name: "JithendraNara",
    role: "Contributor",
    avatar: "https://github.com/JithendraNara.png",
    status: "unread",
  },
  {
    id: 3,
    name: "dewu0224",
    role: "Contributor",
    avatar: "https://github.com/dewu0224.png",
    status: "unread",
  },
  {
    id: 4,
    name: "liyuan97",
    role: "Contributor",
    avatar: "https://github.com/liyuan97.png",
    status: "unread",
  },
];

const MINIMAX_STORIES = [
  {
    id: 1,
    authorId: 1,
    author: "divitkashyap",
    role: "Contributor",
    avatar: "https://github.com/divitkashyap.png",
    time: "1d ago",
    text: "New image analysis skill with OCR, UI review, and chart extraction — vision-powered workflows just got way more capable.",
    pr: {
      title: "feat(vision-analysis): add image analysis skill with OCR, UI review, and chart extraction",
      status: "MERGED",
      number: "#21",
      url: "https://github.com/MiniMax-AI/skills/pull/21",
    },
    reactions: { fire: 5, eyes: 2, hand: 0 },
  },
  {
    id: 2,
    authorId: 2,
    author: "JithendraNara",
    role: "Contributor",
    avatar: "https://github.com/JithendraNara.png",
    time: "1d ago",
    text: "Added Cursor install guide and VS Code note — easier onboarding for new contributors.",
    pr: {
      title: "docs: add Cursor install guide and VS Code note",
      status: "MERGED",
      number: "#25",
      url: "https://github.com/MiniMax-AI/skills/pull/25",
    },
    reactions: { fire: 2, eyes: 1, hand: 0 },
  },
  {
    id: 3,
    authorId: 3,
    author: "dewu0224",
    role: "Contributor",
    avatar: "https://github.com/dewu0224.png",
    time: "1d ago",
    text: "Image processing now uses temp files for jq — fixes Windows command-line length limit crashes.",
    pr: {
      title: "fix(image): use temp files for jq to avoid Windows command-line length limit",
      status: "MERGED",
      number: "#34",
      url: "https://github.com/MiniMax-AI/skills/pull/34",
    },
    reactions: { fire: 3, eyes: 1, hand: 0 },
  },
  {
    id: 4,
    authorId: 4,
    author: "liyuan97",
    role: "Contributor",
    avatar: "https://github.com/liyuan97.png",
    time: "1d ago",
    text: "Plan limits added and video constraints locked to 768P/6s — tighter resource controls for MiniMax generation.",
    pr: {
      title: "feat(minimax): add plan limits & fix video constraints to 768P/6s only",
      status: "MERGED",
      number: "#39",
      url: "https://github.com/MiniMax-AI/skills/pull/39",
    },
    reactions: { fire: 4, eyes: 3, hand: 0 },
  },
];

const EAZO_TEAM = [
  {
    id: 1,
    name: "Chris Li",
    role: "Creator",
    avatar: "https://github.com/unregistered.png",
    status: "unread",
  },
];

const EAZO_STORIES = [
  {
    id: 1,
    authorId: 1,
    author: "Chris Li",
    role: "Creator",
    avatar: "https://github.com/unregistered.png",
    time: "8m ago",
    text: "Removed the phone mockup frame — app now fills the viewport on all screen sizes with a 540px max-width cap.",
    pr: {
      title: "Remove phone mockup and make UI responsive",
      status: "MERGED",
      number: "#12",
      url: "https://github.com/unregistered/code-story/commit/af1a2c0",
    },
    reactions: { fire: 3, eyes: 1, hand: 0 },
  },
  {
    id: 2,
    authorId: 1,
    author: "Chris Li",
    role: "Creator",
    avatar: "https://github.com/unregistered.png",
    time: "10m ago",
    text: "Fixed the flash on StoryViewer mount — skips initial transition and simplifies dismiss styling.",
    pr: {
      title: "Fix StoryViewer mount flash and simplify dismiss style",
      status: "MERGED",
      number: "#11",
      url: "https://github.com/unregistered/code-story/commit/fc55017",
    },
    reactions: { fire: 2, eyes: 1, hand: 0 },
  },
  {
    id: 3,
    authorId: 1,
    author: "Chris Li",
    role: "Creator",
    avatar: "https://github.com/unregistered.png",
    time: "12m ago",
    text: "Added multi-repo support — you can now switch between projects with a dropdown selector.",
    pr: {
      title: "Add multi-repo support with switcher UI",
      status: "MERGED",
      number: "#10",
      url: "https://github.com/unregistered/code-story/commit/b11dd9e",
    },
    reactions: { fire: 5, eyes: 2, hand: 0 },
  },
  {
    id: 4,
    authorId: 1,
    author: "Chris Li",
    role: "Creator",
    avatar: "https://github.com/unregistered.png",
    time: "14m ago",
    text: "UI chrome (header, progress bar) now sits in a fixed overlay above the cube rotation — no more clipping during swipes.",
    pr: {
      title: "Move UI chrome to fixed overlay above cube rotation",
      status: "MERGED",
      number: "#9",
      url: "https://github.com/unregistered/code-story/commit/65cd26b",
    },
    reactions: { fire: 4, eyes: 1, hand: 0 },
  },
  {
    id: 5,
    authorId: 1,
    author: "Chris Li",
    role: "Creator",
    avatar: "https://github.com/unregistered.png",
    time: "20m ago",
    text: "Replaced all mock data with real 24h PR activity pulled from the openclaw repo.",
    pr: {
      title: "Replace mock data with real 24h PR activity from openclaw repo",
      status: "MERGED",
      number: "#8",
      url: "https://github.com/unregistered/code-story/commit/f9d7b16",
    },
    reactions: { fire: 6, eyes: 3, hand: 0 },
  },
  {
    id: 6,
    authorId: 1,
    author: "Chris Li",
    role: "Creator",
    avatar: "https://github.com/unregistered.png",
    time: "29m ago",
    text: "Stories now group by person — swipe left/right moves between people, tap advances within a person's stories.",
    pr: {
      title: "Implement per-person story navigation model",
      status: "MERGED",
      number: "#5",
      url: "https://github.com/unregistered/code-story/commit/e4bb396",
    },
    reactions: { fire: 7, eyes: 2, hand: 1 },
  },
  {
    id: 7,
    authorId: 1,
    author: "Chris Li",
    role: "Creator",
    avatar: "https://github.com/unregistered.png",
    time: "41m ago",
    text: "Redesigned the home screen — added story bubble row with ring indicators and a full posting flow with auto-post timer.",
    pr: {
      title: "Redesign home screen with story bubble row and posting flow",
      status: "MERGED",
      number: "#2",
      url: "https://github.com/unregistered/code-story/commit/f48da80",
    },
    reactions: { fire: 8, eyes: 4, hand: 1 },
  },
  {
    id: 8,
    authorId: 1,
    author: "Chris Li",
    role: "Creator",
    avatar: "https://github.com/unregistered.png",
    time: "47m ago",
    text: "Initial build — story viewer with Instagram-style cube transitions, AI-generated commit summaries, and reaction support.",
    pr: {
      title: "Initial commit: story viewer with cube transitions and AI summaries",
      status: "MERGED",
      number: "#1",
      url: "https://github.com/unregistered/code-story/commit/70059ca",
    },
    reactions: { fire: 12, eyes: 5, hand: 2 },
  },
];

export const REPOS = [
  {
    id: "openclaw",
    name: "Openclaw",
    fullName: "openclaw/openclaw",
    team: OPENCLAW_TEAM,
    me: OPENCLAW_ME,
    pendingPost: OPENCLAW_PENDING_POST,
    stories: OPENCLAW_STORIES,
  },
  {
    id: "minimax-skills",
    name: "MiniMax Skills",
    fullName: "MiniMax-AI/skills",
    team: MINIMAX_TEAM,
    me: null,
    pendingPost: null,
    stories: MINIMAX_STORIES,
  },
  {
    id: "eazo-code-story",
    name: "Eazo Code Story",
    fullName: "unregistered/code-story",
    team: EAZO_TEAM,
    me: null,
    pendingPost: null,
    stories: EAZO_STORIES,
  },
];
