export const TEAM = [
  {
    id: 1,
    name: "Tak Hoffman",
    role: "Contributor",
    avatar: "https://github.com/Takhoffman.png",
    status: "unread",
  },
  {
    id: 2,
    name: "Harold Hunter",
    role: "GIPHY",
    avatar: "https://github.com/huntharo.png",
    status: "unread",
  },
  {
    id: 3,
    name: "Ayaan Zaidi",
    role: "Maintainer",
    avatar: "https://github.com/obviyus.png",
    status: "unread",
  },
  {
    id: 4,
    name: "Robin Waslander",
    role: "Mblock BV",
    avatar: "https://github.com/hydro13.png",
    status: "missing",
  },
  {
    id: 5,
    name: "Peter Steinberger",
    role: "Clawdfather",
    avatar: "https://github.com/steipete.png",
    status: "unread",
  },
];

export const ME = {
  id: 0,
  name: "Gustavo Santana",
  role: "Contributor",
  avatar: "https://github.com/gumadeiras.png",
  status: "posted",
};

export const PENDING_POST = {
  text: "Matrix login no longer fails when primary credentials are unavailable — smoother auth experience for federated users.",
  ticket: { title: "MTX-18 Auth fallback", status: "MERGED" },
  landedAt: Date.now() - 2 * 60 * 1000,
  autoPostAt: Date.now() + 8 * 60 * 1000,
};

export const STORIES = [
  {
    id: 1,
    authorId: 1,
    author: "Tak Hoffman",
    role: "Contributor",
    avatar: "https://github.com/Takhoffman.png",
    time: "4h ago",
    text: "Dashboard setup now guides users with clearer prompts — fewer drop-offs at onboarding.",
    pr: {
      title: "Improve dashboard setup command copy UX",
      status: "MERGED",
      number: "#56551",
      url: "https://github.com/vercel/next.js/pull/56551",
    },
    reactions: { fire: 4, eyes: 2, hand: 0 },
  },
  {
    id: 2,
    authorId: 2,
    author: "Harold Hunter",
    role: "GIPHY",
    avatar: "https://github.com/huntharo.png",
    time: "1h ago",
    text: "Agents can now run code natively via xAI — unlocks autonomous debugging and data analysis workflows.",
    pr: null,
    ticket: {
      title: "XAI-42 Plugin code_execution",
      status: "IN REVIEW",
    },
    reactions: { fire: 6, eyes: 3, hand: 1 },
  },
  {
    id: 3,
    authorId: 3,
    author: "Ayaan Zaidi",
    role: "Maintainer",
    avatar: "https://github.com/obviyus.png",
    time: "10h ago",
    text: "Eliminated a race condition that caused silent process crashes — improves reliability for long-running tasks.",
    pr: null,
    ticket: {
      title: "QA-301 Process settlement",
      status: "OPEN",
    },
    reactions: { fire: 2, eyes: 4, hand: 1 },
  },
  {
    id: 4,
    authorId: 5,
    author: "Peter Steinberger",
    role: "Clawdfather",
    avatar: "https://github.com/steipete.png",
    time: "20m ago",
    text: "Plugin system now loads provider contracts reliably — third-party integrations just work out of the box.",
    pr: {
      title: "refactor(plugins): expose bundled onboard helpers",
      status: "MERGED",
      number: "#56620",
      url: "https://github.com/vercel/next.js/pull/56620",
    },
    reactions: { fire: 9, eyes: 2, hand: 0 },
  },
  {
    id: 5,
    authorId: 0,
    author: "Gustavo Santana",
    role: "Contributor",
    avatar: "https://github.com/gumadeiras.png",
    time: "16h ago",
    text: "Matrix login no longer fails when primary credentials are unavailable — smoother auth experience for federated users.",
    pr: null,
    ticket: {
      title: "MTX-18 Auth fallback",
      status: "MERGED",
    },
    reactions: { fire: 3, eyes: 1, hand: 0 },
  },
  {
    id: 6,
    authorId: 1,
    author: "Tak Hoffman",
    role: "Contributor",
    avatar: "https://github.com/Takhoffman.png",
    time: "2h ago",
    text: "Locale detection now respects OS-level overrides — multilingual users finally get the right default language.",
    pr: {
      title: "fix(i18n): prefer OS locale over browser hint",
      status: "MERGED",
      number: "#56580",
      url: "https://github.com/vercel/next.js/pull/56580",
    },
    reactions: { fire: 3, eyes: 1, hand: 0 },
  },
  {
    id: 7,
    authorId: 5,
    author: "Peter Steinberger",
    role: "Clawdfather",
    avatar: "https://github.com/steipete.png",
    time: "15m ago",
    text: "Hot-reload no longer drops WebSocket connections mid-edit — live preview stays in sync during rapid saves.",
    pr: {
      title: "fix(hmr): keep WS alive across module invalidations",
      status: "OPEN",
      number: "#56635",
      url: "https://github.com/vercel/next.js/pull/56635",
    },
    reactions: { fire: 5, eyes: 3, hand: 1 },
  },
];
